#!/usr/bin/env python3
"""Generate src/renderer/jpeg-tables.js from the decompiled Huawei KVM client.

Extracting the constants programmatically avoids transcription errors in the
64-byte quantization tables.
"""
import json, re, os, sys

DECOMP = "<decompiled-vendor-sources>/com/library/decoder"
OUT = sys.argv[1] if len(sys.argv) > 1 else "src/renderer/jpeg-tables.js"

def java_bytes(path, name):
    src = open(path, encoding="utf-8", errors="replace").read()
    m = re.search(r"\b" + name + r"\s*=\s*new byte\[\]\s*\{(.*?)\}", src, re.S)
    if not m:
        raise SystemExit(f"找不到 {name} in {path}")
    return bytes((v + 256) % 256 for v in (int(x) for x in re.findall(r"-?\d+", m.group(1))))

JP = os.path.join(DECOMP, "JPEGData.java")
DQ = os.path.join(DECOMP, "DQTZData.java")

soi_app0 = java_bytes(JP, "HEAD_SYN_SOI_APPO")
sofsos   = java_bytes(JP, "HEAD_SYN_SOF_SOS")
tail     = java_bytes(JP, "TAIL")
sof_tables = {
    "444": java_bytes(JP, "HEAD_SYN_SOF_444"),
    "420": java_bytes(JP, "HEAD_SYN_SOF_420"),
}
# dqttags 0..9 -> quality 10..100
dqt = {"Y": [], "U": [], "V": []}
for tag in range(10):
    q = tag * 10 + 10
    for comp in ("Y", "U", "V"):
        dqt[comp].append(java_bytes(DQ, f"HEAD_SYN_DQT_{comp}_{q}").hex())

def hexs(b):
    return b.hex()

js = f"""// AUTO-GENERATED by tools/gen-jpeg-tables.py — do not edit by hand.
// Source: decompiled com/library/decoder/{{JPEGData,DQTZData}}.java
// These are the synthetic JPEG headers the vendor client prepends to the raw
// entropy-coded scan data the BMC sends for each 64x64 JPEG block.

const HEAD_SYN_SOI_APPO = "{hexs(soi_app0)}";
const HEAD_SYN_SOF_SOS  = "{hexs(sofsos)}";
const TAIL              = "{hexs(tail)}";
export const HEAD_SYN_SOF_444 = "{hexs(sof_tables['444'])}";
export const HEAD_SYN_SOF_420 = "{hexs(sof_tables['420'])}";

// DQT tables indexed by dqttags (0..9) == quality 10..100
const DQT_Y = {json.dumps(dqt['Y'], indent=0)};
const DQT_U = {json.dumps(dqt['U'], indent=0)};
const DQT_V = {json.dumps(dqt['V'], indent=0)};

function hexToBytes(hex) {{
  const out = new Uint8Array(hex.length >> 1);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16);
  return out;
}}

const headCache = new Array(10);

/** Synthetic JPEG header bytes for a given dqttags value (0..9). Cached. */
export function synHeadBytes(dqttags) {{
  const t = Math.max(0, Math.min(9, dqttags | 0));
  if (!headCache[t]) {{
    headCache[t] = hexToBytes(HEAD_SYN_SOI_APPO + DQT_Y[t] + DQT_U[t] + DQT_V[t] + HEAD_SYN_SOF_444 + HEAD_SYN_SOF_SOS);
  }}
  return headCache[t];
}}

const tailBytes = hexToBytes(TAIL);

/**
 * Assemble a complete JPEG from a raw entropy-coded scan.
 * @param {{Uint8Array}} rawScan
 * @param {{number}} dqttags 0..9
 * @returns {{Uint8Array}}
 */
export function buildJpegBytes(rawScan, dqttags) {{
  const head = synHeadBytes(dqttags);
  const out = new Uint8Array(head.length + rawScan.length + tailBytes.length);
  out.set(head, 0);
  out.set(rawScan, head.length);
  out.set(tailBytes, head.length + rawScan.length);
  return out;
}}
"""
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write(js)
print(f"写入 {OUT}  ({len(js)} 字节)")
print(f"  SOI/APP0 {len(soi_app0)}B, SOF_444 {len(sof_tables['444'])}B, SOF_420 {len(sof_tables['420'])}B, DHT+DRI+SOS {len(sofsos)}B, TAIL {len(tail)}B")
print(f"  DQT 档数 {len(dqt['Y'])}，每张 {len(bytes.fromhex(dqt['Y'][0]))}B")
print(f"  合成头总长 = {len(soi_app0) + 3*69 + len(sof_tables['444']) + len(sofsos)}B")
